<?php
return[
    'AVISO_LEGAL'              => 'Legal Notice',
    'ESTA_PAGINA_WEB'          => 'This website is owned by URNOVA, S.L.U. (hereinafter, URNOVA).',
    'CIF'                      => 'CIF: B-79308755.',
    'DOMICILIO_SOCIAL'         => 'Registered office: C/ Joan Maragall, 38, 07006 – Palma de Mallorca.',
    'DATOS_DE_INSCRIPCION'     => 'Registration data in the Commercial Registry of Palma de Mallorca: Volume 2119, Book 0, Folio 82, Registration 9, Page PM-50.035.',
    'CONTACTO'                 => 'Contact:',
    'DIRECCION_DE_CORREO_E'    => 'Email address:',
    'TELEFONO'                 => 'Phone:',
    'EN_CUALQUIER_MOMENTO'     => 'At any time, the interested party may save or print this Legal Notice.',
    'LA_UTILIZACION_DE_ESTA'   => 'The use of this Web page attributes the condition of user to whoever does it and implies the acceptance of all the conditions included in this Legal Notice.',
    'TODOS_LOS_CONTENIDOS'     => 'All the contents of this website (texts, photographs, graphics, images, technology, software, links, audiovisual content, graphic design, source code, etc.), as well as trademarks and other distinctive signs, are the property of URNOVA, the user not acquiring any rights over them for the mere use of this Web.',
    'QUEDA_PROHIBIDO'          => 'It is forbidden any use of this website that has as purpose or results in injury to property, rights or interests of URNOVA, the rest of the companies of the Group, its customers, suppliers or third parties. It is also prohibited to make any use of this website that alters, damages or renders URNOVA networks, servers, equipment, products and computer programs unusable.',
    'EL_USUARIO_DEBERA'        => 'The user must refrain from: a) reproducing, copying, distributing, making available to third parties, publicly communicating, transforming or modifying the contents of this website, except in cases contemplated by law or expressly authorized by URNOVA or by the owner of said rights; b) reproducing or copying for private use the software or databases existing on this website, as well as communicating them publicly or making them available to third parties when this entails their reproduction; c) extract or reuse all or a substantial part of the contents of this website. In any case, the use or reproduction of content or databases that is expressly authorized by URNOVA is excepted from the foregoing.',
    'EL_USUARIO_QUE_QUIERA'    => 'The User who wishes to introduce links to this Website must comply with the following conditions: a) there may be no frames of any type that surround the Website or allow it to be viewed through different Internet addresses or together with contents external to this Website, can not be established, so that it produces, or may produce, error or confusion in the users about the origin of the service or its content, implies an act of comparison or unfair imitation, serves to take advantage of the reputation, brand and prestige of URNOVA, of the rest of the companies of the Group or its customers or is done in any other way that is prohibited by law; b) from the page where the link is made, no false or inaccurate statements about URNOVA, about the quality of its services or about its suppliers, employees or customers or the rest of the Group companies may be made; c) The sender can not use the brand or any other distinctive URNOVA sign on its website, except in cases authorized by law or expressly permitted by URNOVA; d) the page that establishes the link must observe the current legislation and may not dispose of or link with illicit, harmful, contrary to morality and good customs, that produce or may produce the false idea that URNOVA supports or supports the ideas, manifestations or actions of the sender or that are inadequate in relation to the activity developed by URNOVA, the rest of the Group companies and their clients, taking into account the contents and the general theme of the Web page where the link is established.',
    'ESTA_WEB_PUEDE'           => 'This website may include technical linking devices that allow the user to access other Internet pages (links). URNOVA does not know the contents and services of the links and therefore is not responsible for the damages derived from its lack of quality, outdated, unavailability, error, uselessness or illegality and does not respond to the statements made or the contents or services provided through them. If any user is aware that the links refer to pages whose contents or services are illegal, harmful, degrading, violent or immoral, you can contact URNOVA indicating it.',
    'EL_PRESENTE_AVISO'        => 'This Legal Notice is governed entirely by Spanish law. The user undertakes to make correct use of this website in accordance with the Law, with this Legal Notice, as well as with the other conditions, regulations and instructions that, where appropriate, may be applicable.',
];