<?php
return[
    'POLITICA_DE_PRIVACIDAD'   => 'Datenschutzrichtlinie',
    'A_LOS_EFECTOS_DE_LO'      => 'Im Sinne der Bestimmungen des Organgesetzes 15/1999 vom 13. Dezember über den Schutz personenbezogener Daten werden die Benutzer dieser Website darüber informiert, dass die persönlichen Daten, die sie durch sie bereitstellen, Sowohl beim Ausfüllen eines Formulars als auch per E-Mail oder auf andere Weise werden diese Datenschutzerklärungen behandelt.',
    'LOS_DATOS_FACILITADOS'    => 'Die zur Verfügung gestellten Daten werden Teil der Dateien, für die URNOVA, S.L.U. verantwortlich ist, die im Generalregister der spanischen Agentur für Datenschutz registriert sind. Je nach dem Zweck, für den die Daten bereitgestellt werden, werden diese verarbeitet, um auf Ihre Anfrage, Fragen, Vorschlag oder Zweifel zu antworten.',
    'SI_SE_NOS_PROPORCIONA'    => 'Wenn uns Daten von Dritten zur Verfügung gestellt werden, muss die Person, die dies tut, unter Einhaltung ihrer Verantwortung die betroffenen Parteien über die Bestimmungen dieser Klausel informieren und ihre Zustimmung im Voraus einholen.',
    'EN_TODO_CASO'             => 'In jedem Fall können die Rechte auf Zugang, Berichtigung, Löschung und Widerspruch unter der folgenden Adresse ausgeübt werden: C / Joan Maragall, 38, 07002 (Palma de Mallorca) oder per E-Mail an',
    'POLITICA_DE_COOKIES'      => 'COOKIES-POLITIK',
    'UNA_COOKIE_ES_UN_FICHERO' => 'Ein Cookie ist eine Datei, die beim Zugriff auf bestimmte Webseiten auf Ihren Computer heruntergeladen wird. Cookies ermöglichen es einer Webseite unter anderem, Informationen über die Surfgewohnheiten eines Nutzers oder dessen Geräte zu speichern und abzurufen und je nach den darin enthaltenen Informationen und der Art und Weise, in der ihre Geräte genutzt werden, können dazu dienen, es zu erkennen.',
    'NO_OBSTANTE_ESTOS_MEDIOS' => 'Diese Mittel beziehen sich jedoch nur auf die Anzahl der besuchten Seiten, die Stadt, zu der die IP-Adresse, von der aus auf sie zugegriffen wird, zugewiesen wird, die Anzahl neuer Benutzer, die Häufigkeit und Rückfälligkeit der Besuche, die Zeit des Besuchs der Browser oder der Betreiber oder die Art des Terminals, von dem aus der Besuch getätigt wurde. In keinem Fall werden Daten über den Namen, den Nachnamen oder die Postanschrift erhalten, mit denen sich der Benutzer verbunden hat.',
    'LAS_COOKIES_UTILIZADAS'   => 'Die Cookies, die in dieser Webseite verwendet werden, und der spezifische Zweck von jedem von ihnen sind die folgenden:',
    'COOKIE_GA'                => 'Cookie _ga: Dieser Cookie soll einzigartige Besuche kontrollieren. Wenn ein Benutzer zum ersten Mal die URNOVA S.L.U.-Website aufruft, wird  dieser Cookie über einen Browser installiert. Wenn dieser Nutzer unsere Seite erneut mit demselben Browser öffnet, wird der Cookie berücksichtigen, dass es sich um denselben Benutzer handelt. Nur wenn der Nutzer den Browser ändert, berücksichtigt Google Analytics einen anderen Nutzer.',
    'COOKIE_DATR'              => 'Cookie-Datr: Facebook-Cookies, die das Einloggen auf der Website über den Facebook-Account ermöglichen sollen.',
    'PUEDE_USTED_PERMITIR'     => 'Sie können die auf Ihrem Computer installierten Cookies zulassen, blockieren oder löschen, indem Sie die Optionen Ihres Browsers konfigurieren. In den folgenden Links finden Sie Informationen zu den gängigsten Browsern:',
    'LE_INFORMAMOS_NO_OBSTANTE'=> 'Wir informieren Sie jedoch über die Möglichkeit, dass die Deaktivierung eines Cookies die Navigation oder die Bereitstellung der auf dieser Website angebotenen Dienste verhindert oder behindert.',
];