<?php
return[
    'POLITICA_DE_PRIVACIDAD'   => 'POLÍTICA DE PRIVACIDAD',
    'A_LOS_EFECTOS_DE_LO'      => 'A los efectos de lo previsto en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, se informa a los usuarios de esta página Web de que los datos de carácter personal que faciliten a través de ella, tanto cumplimentando cualquier formulario, como a través de correo electrónico o por cualquier otro medio serán tratados de conformidad con la presente Política de Protección de Datos.',
    'LOS_DATOS_FACILITADOS'    => 'Los datos facilitados pasarán a formar parte de los ficheros de los que es responsable URNOVA, S.L.U. y que se encuentran convenientemente inscritos en el Registro General de la Agencia Española de Protección de Datos. En función del fin para el que los datos sean facilitados, estos serán tratados con objeto de dar respuesta a su solicitud, consulta, sugerencia o duda.',
    'SI_SE_NOS_PROPORCIONA'    => 'Si se nos proporcionan datos de terceros, la persona que lo haga deberá, bajo su responsabilidad, informar al afectado de lo dispuesto en esta cláusula y obtener previamente su consentimiento.',
    'EN_TODO_CASO'             => 'En todo caso, pueden ejercerse los derechos de acceso, rectificación, cancelación y oposición en la siguiente dirección: C/ Joan Maragall, 38, 07002 (Palma de Mallorca) o mandando un e-mail a',
    'POLITICA_DE_COOKIES'      => 'POLÍTICA DE COOKIES',
    'UNA_COOKIE_ES_UN_FICHERO' => 'Una cookie es un fichero que se descarga en su ordenador al acceder a determinadas páginas web. Las cookies permiten a una página web, entre otras cosas, almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo y, dependiendo de la información que contengan y de la forma en que se utilice su equipo, pueden servir para reconocerlo.',
    'NO_OBSTANTE_ESTOS_MEDIOS' => 'No obstante, estos medios sólo obtienen información relacionada con el número de páginas visitas, la ciudad a la que está asignada la dirección IP desde la que se accede, el número de nuevos usuarios, la frecuencia y reincidencia de las visitas, el tiempo de visita, el navegador o el operador o tipo de terminal desde el que se realiza la visita. En ningún caso se obtienen datos sobre el nombre, apellidos o dirección postal desde la que el usuario se ha conectado.',
    'LAS_COOKIES_UTILIZADAS'   => 'Las cookies utilizadas en esta página Web y la concreta finalidad de cada una de ellas son las siguientes:',
    'COOKIE_GA'                => 'Cookie _ga: Esta cookie tiene como finalidad controlar las visitas únicas. La primera vez que un usuario entre en el sitio Web de URNOVA, S.L.U. a través de un navegador se instalará esta cookie. Cuando este usuario vuelva a entrar en nuestra página con el mismo navegador, la cookie considerará que es el mismo usuario. Solo en el caso de que el usuario cambie de navegador, Google Analytics lo considerará otro usuario.',
    'COOKIE_DATR'              => 'Cookie datr: Cookies de Facebook que tienen por finalidad posibilitar el logueo en el sitio web a través de la cuenta de Facebook.',
    'PUEDE_USTED_PERMITIR'     => 'Puede usted permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones de su navegador. Puede encontrar información sobre cómo hacerlo, en relación con los navegadores más comunes, en los links que se incluyen a continuación:',
    'LE_INFORMAMOS_NO_OBSTANTE'=> 'Le informamos, no obstante, de la posibilidad de que la desactivación de alguna cookie impida o dificulte la navegación o la prestación de los servicios ofrecidos en esta Web.',
];